# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 27fede4806f672102e731b030d9a489b4b4265322a10eb0cdfdd27a7748748ffbb95ac28be9db648c455d9b031df981c3ddf3cc0d4909d6950559e05933ddac3

test:
  secret_key_base: 5df95cfff993723ab0e1e24b55231a405ce6dc1c971585f1d889484170783b7da59c52fb60267b11d8897849bc2cf831cbfdb95a15ef8843ca68dbb0d4505d0b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
